artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_root: "vladimir7542/for_whisper_ft1_prepared"
  local_data_file: artifacts/data_ingestion/data.hf


prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.pt
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.pt


training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.pt